name: influencer_dashboard

description: "Direct Brand Collabs. Find, pitch, and manage paid influencer campaigns. Get matched and get paid faster."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core packages
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  dio: ^5.4.3
  webview_flutter: ^4.10.0
  dropdown_search: ^5.0.6
  pretty_dio_logger: ^1.4.0
  image_picker: ^1.0.4
  permission_handler: ^11.3.0
  image_cropper: ^5.0.1
  shimmer: ^3.0.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.1.0
  photo_view: ^0.14.0
  socket_io_client: ^3.1.2
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4


dependency_overrides:
    webview_flutter_android: ^3.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/instagram.png
    - assets/cb_icon.png
    - assets/youtube.png
    - assets/logo.png
    - assets/ai.png
    - assets/welcome_logo.png
    - assets/login_bg.png
    - assets/placeholder.png
    - assets/avatar.png
    - assets/home_card_1.png

    - assets/banner11.png
    - assets/banner2.png
    - assets/banner3.png
    - assets/banner4.png
    - assets/banner5.png
    - assets/banner6.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

# 🚀 App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/cb_icon.png"          # <-- your app logo
  adaptive_icon_background: "#FFFFFF"       # <-- or brand purple #671DD1
  adaptive_icon_foreground: "assets/cb_icon.png"

# 💜 Splash Screen Configuration
flutter_native_splash:
  color: "#671DD1"
  image: assets/cb_icon.png
  android: true
  ios: true
